"""added bookings

Revision ID: 43059a6e7ce4
Revises: 7fe8164fabf5
Create Date: 2020-11-01 07:37:54.010572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43059a6e7ce4'
down_revision = '7fe8164fabf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    # ### end Alembic commands ###
