"""added last logged in and out timing

Revision ID: 57449382557f
Revises: 97d3dc39b4b2
Create Date: 2020-11-01 08:56:57.549831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57449382557f'
down_revision = '97d3dc39b4b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'slot', ['slot_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_logged_in', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('last_logged_out', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_logged_out')
        batch_op.drop_column('last_logged_in')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'channel', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'channel', ['slot_id'], ['id'])

    # ### end Alembic commands ###
