"""Added Slots Model

Revision ID: 850c95018c98
Revises: 954e1a3caa8d
Create Date: 2020-10-29 23:08:26.590265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850c95018c98'
down_revision = '954e1a3caa8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=4), nullable=True),
    sa.Column('end_time', sa.String(length=4), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slots')
    # ### end Alembic commands ###
