"""added last logged in and out timing

Revision ID: d6079eb9668e
Revises: b41482362295
Create Date: 2020-11-01 08:53:06.273514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6079eb9668e'
down_revision = 'b41482362295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.create_foreign_key(None, 'booking', 'slot', ['slot_id'], ['id'])
    op.create_foreign_key(None, 'booking', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('last_logged_in', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('last_logged_out', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_logged_out')
    op.drop_column('user', 'last_logged_in')
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.create_foreign_key(None, 'booking', 'channel', ['slot_id'], ['id'])
    op.create_foreign_key(None, 'booking', 'channel', ['user_id'], ['id'])
    # ### end Alembic commands ###
