"""Changed to Slot

Revision ID: dbadf722ec8a
Revises: 850c95018c98
Create Date: 2020-10-29 23:57:00.996390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbadf722ec8a'
down_revision = '850c95018c98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=4), nullable=True),
    sa.Column('end_time', sa.String(length=4), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('slots')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slots',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('start_time', sa.VARCHAR(length=4), nullable=True),
    sa.Column('end_time', sa.VARCHAR(length=4), nullable=True),
    sa.Column('channel_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('slot')
    # ### end Alembic commands ###
